name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - uses: js-devtools/npm-publish@v3
        if: github.ref == 'refs/heads/main'
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
