name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - uses: raviqqe/pnpm-publish@v1
        if: github.ref == 'refs/heads/main'
        with:
          access: public
          token: ${{ github.ref == 'refs/heads/main' && secrets.NPM_TOKEN || '' }}
